# Generated by Django 5.1.2 on 2024-12-04 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCarrito',
            fields=[
                ('estado_carrito_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'estado_carrito',
            },
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('estado_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'estado_pedido',
            },
        ),
        migrations.CreateModel(
            name='MetodoEnvio',
            fields=[
                ('envio_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('costo', models.IntegerField()),
                ('tiempo_estimado', models.CharField(max_length=20)),
                ('habilitado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'metodo_envio',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('perfil_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'perfil',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=30, null=True)),
                ('informacion_nutricional', models.TextField(blank=True, null=True)),
                ('dosificacion', models.TextField(blank=True, null=True)),
                ('contenido_envase', models.CharField(blank=True, max_length=30, null=True)),
                ('precio', models.IntegerField()),
                ('imagen_url', models.CharField(blank=True, max_length=255, null=True)),
                ('habilitado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('carrito_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carritos', to='AppVitamin.estadocarrito')),
            ],
            options={
                'db_table': 'carrito',
            },
        ),
        migrations.CreateModel(
            name='ProductoCarrito',
            fields=[
                ('producto_carrito_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='AppVitamin.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to='AppVitamin.producto')),
            ],
            options={
                'db_table': 'producto_carrito',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('primer_apellido', models.CharField(max_length=20)),
                ('segundo_apellido', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('contrasena', models.CharField(max_length=128)),
                ('direccion_envio', models.TextField(blank=True, null=True)),
                ('intentos_inicio_sesion', models.IntegerField(default=0)),
                ('cuenta_suspendida', models.BooleanField(default=False)),
                ('perfil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='AppVitamin.perfil')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('metodo_pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('tipo_tarjeta', models.CharField(choices=[('Visa', 'Visa'), ('MasterCard', 'MasterCard'), ('Amex', 'American Express'), ('Discover', 'Discover'), ('Otro', 'Otro')], max_length=20)),
                ('numero_tarjeta', models.CharField(max_length=16)),
                ('fecha_expiracion', models.CharField(max_length=7)),
                ('cvv', models.CharField(max_length=4)),
                ('habilitado', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago', to='AppVitamin.usuario')),
            ],
            options={
                'db_table': 'metodo_pago',
            },
        ),
        migrations.CreateModel(
            name='HistorialAcciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('tabla', models.CharField(max_length=50)),
                ('registro_id', models.IntegerField()),
                ('detalles', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppVitamin.usuario')),
            ],
            options={
                'db_table': 'historial_acciones',
            },
        ),
        migrations.AddField(
            model_name='carrito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to='AppVitamin.usuario'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('venta_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('total', models.IntegerField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppVitamin.estadopedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='AppVitamin.usuario')),
            ],
            options={
                'db_table': 'venta',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('detalle_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='AppVitamin.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='AppVitamin.venta')),
            ],
            options={
                'db_table': 'detalle_venta',
            },
        ),
    ]
